"""Create products table

Revision ID: a5619dcbd41f
Revises: b373fd1ed044
Create Date: 2024-08-13 00:27:21.019658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5619dcbd41f'
down_revision = 'b373fd1ed044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('star', sa.Integer(), nullable=True))        
        batch_op.add_column('product', sa.Column('category', sa.String(length=100), nullable=False, server_default='Unknown'))
        batch_op.alter_column('product', 'category', server_default=None)
        
                
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('star')
        batch_op.drop_column('image_url')
        batch_op.drop_column('category')
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
    
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        
        
# ### end Alembic commands ###

#Add the column with a default value
def upgrade():
    op.add_column('product', sa.Column('category', sa.String(length=100), nullable=False, server_default='Uncategorized'))

def downgrade():
    op.drop_column('product', 'category')

   
